<template>
  <div class="minor-workspace"><aside class="step-rail"><div class="rail-heading"><b>{{ major.processName }}</b><small>小步骤编排</small></div><button v-for="(step,index) in major.steps" :key="step.key" class="step-item" :class="{ active:index===selectedIndex }" draggable="true" @click="selectedIndex=index" @dragstart="dragExisting($event,index)" @dragover.prevent @drop.stop="dropAt($event,index)"><span>{{ String(index+1).padStart(2,'0') }}</span><b>{{ step.stepName || '未命名步骤' }}</b><small>{{ parameterSummary(step) }}</small></button><a-button v-if="!readonly" type="dashed" block @click="addStep()">＋ 新建小步骤</a-button><div class="step-templates"><small>模板可重复拖入</small><button v-for="name in stepTemplates" :key="name" draggable="true" :disabled="readonly" @dragstart="dragTemplate($event,name)" @dblclick="addStep(name)">{{ name }}</button></div></aside>
    <main v-if="selectedStep" class="step-editor"><header class="editor-header"><div><span class="crumb">{{ major.processName }} / 小步骤 {{ selectedIndex+1 }}</span><h3>{{ selectedStep.stepName || '未命名步骤' }}</h3><p>{{ parameterSummary(selectedStep) }}</p></div><a-space><a-button v-if="!readonly" @click="copyStep">复制</a-button><a-button v-if="!readonly" danger @click="removeStep">删除</a-button></a-space></header>
      <section class="section"><div class="section-title"><b>基础操作参数</b><a-button v-if="!readonly" type="link" size="small" @click="expanded.basic=!expanded.basic">{{ expanded.basic?'收起':'编辑' }}</a-button></div><div v-if="!expanded.basic" class="summary-grid"><span>设备：{{ selectedStep.equipment || '未设置' }}</span><span>{{ parameterSummary(selectedStep) }}</span><span>要求：{{ selectedStep.instruction || '未设置' }}</span></div><a-form v-else layout="vertical"><a-row :gutter="10"><a-col :span="12"><a-form-item label="步骤名称"><a-input v-model:value="selectedStep.stepName" :disabled="readonly" /></a-form-item></a-col><a-col :span="12"><a-form-item label="步骤类型"><a-select v-model:value="selectedStep.stepType" :disabled="readonly" :options="stepTypes" /></a-form-item></a-col></a-row><a-row :gutter="10"><a-col :span="8"><a-form-item label="参数 1"><a-input v-model:value="selectedStep.parameter1Name" :disabled="readonly" placeholder="温度" /></a-form-item></a-col><a-col :span="8"><a-form-item label="值"><a-input v-model:value="selectedStep.parameter1Value" :disabled="readonly" /></a-form-item></a-col><a-col :span="8"><a-form-item label="单位"><a-input v-model:value="selectedStep.parameter1Unit" :disabled="readonly" /></a-form-item></a-col></a-row><a-row :gutter="10"><a-col :span="8"><a-form-item label="参数 2"><a-input v-model:value="selectedStep.parameter2Name" :disabled="readonly" placeholder="时间" /></a-form-item></a-col><a-col :span="8"><a-form-item label="值"><a-input v-model:value="selectedStep.parameter2Value" :disabled="readonly" /></a-form-item></a-col><a-col :span="8"><a-form-item label="单位"><a-input v-model:value="selectedStep.parameter2Unit" :disabled="readonly" /></a-form-item></a-col></a-row><a-form-item label="设备"><a-input v-model:value="selectedStep.equipment" :disabled="readonly" /></a-form-item><a-form-item label="操作要求"><a-textarea v-model:value="selectedStep.instruction" :disabled="readonly" :rows="2" /></a-form-item></a-form></section>
      <section class="section"><div class="section-title"><b>本步骤投料</b><a-button v-if="!readonly" type="link" size="small" @click="addMaterial">＋ 添加投料</a-button></div><p class="hint">外部物料可填写物料/配方 ID；中间产物仅可选择前序步骤继续流转的产出，<b>不进入物料库</b>。</p><div v-for="(material,index) in selectedStep.materials" :key="material.key" class="material-row"><a-select v-model:value="material.sourceType" :disabled="readonly" :options="sourceTypes" @change="onSourceChange(material)" /><a-select v-if="material.sourceType==='STEP_OUTPUT'" v-model:value="material.sourceStepOutputId" :disabled="readonly" :options="previousOutputsFor(material)" placeholder="选择前序产出" @change="applyOutputSource(material)" /><template v-else><a-input v-model:value="material.formulaMaterialId" :disabled="readonly" placeholder="配方物料 ID" /><a-input v-model:value="material.materialCode" :disabled="readonly" placeholder="物料编码" /></template><a-select v-model:value="material.materialRole" :disabled="readonly" :options="materialRoles" @change="ensurePrimaryMaterial(material)" /><a-input v-model:value="material.materialName" :disabled="readonly" placeholder="物料名称" /><a-input-number v-model:value="material.weightKg" :disabled="readonly" :min="0" addon-after="kg" /><a-button v-if="!readonly" type="text" danger @click="selectedStep.materials.splice(index,1)">删除</a-button></div></section>
      <section class="section"><div class="section-title"><b>产出与中间状态</b><a-button v-if="!readonly" type="link" size="small" @click="addOutput">＋ 添加产出</a-button></div><p class="hint">中间产物仅在本工艺版本流转，<b>不进入物料库</b>。每步最多一项主料产出。</p><div v-for="(output,index) in outputs" :key="output.key" class="output-row"><a-select v-model:value="output.outputType" :disabled="readonly" :options="outputTypes" /><a-input v-model:value="output.outputName" :disabled="readonly" placeholder="产出名称/中间状态" /><a-select v-model:value="output.materialState" :disabled="readonly" :options="states" /><a-input-number v-model:value="output.weightKg" :disabled="readonly" :min="0" addon-after="kg" /><a-checkbox v-model:checked="output.primaryOutput" :disabled="readonly || output.primaryOutput && false" @change="ensurePrimaryOutput(output)">主料产出</a-checkbox><a-checkbox v-model:checked="output.continueFlow" :disabled="readonly">继续流转</a-checkbox><a-input v-model:value="output.remark" :disabled="readonly" placeholder="备注" /><a-button v-if="!readonly" type="text" danger @click="outputs.splice(index,1)">删除</a-button></div></section>
      <section class="section live"><div><b>得率摘要</b><span>小步骤 {{ percent(stepYield.mainYieldPercent) }} · 大工序 {{ percent(majorYield.mainYieldPercent) }}</span></div><div><b>关键参数</b><span>{{ parameterSummary(selectedStep) }}</span></div></section>
      <ControlPointEditor v-model="selectedControlPoints" :readonly="readonly" />
    </main><main v-else class="no-step">先添加一个小步骤</main>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import { calculateMajorProcessYield, calculateMinorStepYield, nextProcessKey, normalizeProcessPlan, type MajorProcessDraft, type MinorProcessStepDraft, type ProcessStepMaterialDraft, type StepOutputDraft } from "@rnd/shared";
import ControlPointEditor from "./ControlPointEditor.vue";
const props=defineProps<{modelValue:MajorProcessDraft;readonly?:boolean}>(); const emit=defineEmits<{"update:modelValue":[value:MajorProcessDraft]}>(); const selectedIndex=ref(0); const expanded=reactive({basic:false}); const dragPayload=ref<{kind:"template"|"existing";name?:string;index?:number}|null>(null);
const major=computed(()=>props.modelValue); const selectedStep=computed(()=>major.value.steps[selectedIndex.value]); const selectedControlPoints=computed({get:()=>selectedStep.value?.controlPoints||[],set:value=>{if(selectedStep.value)selectedStep.value.controlPoints=value;}}); const outputs=computed(()=>selectedStep.value?.outputs || (selectedStep.value!.outputs=[]));
const previousOutputs=computed(()=>major.value.steps.slice(0,selectedIndex.value).flatMap((step,stepIndex)=>(step.outputs||[]).filter(output=>output.continueFlow).map(output=>({label:`步骤 ${stepIndex+1} · ${output.outputName || '未命名产出'}（不进入物料库）`,value:output.id||output.key,output}))));
const stepTemplates=["验收","解冻","清洗","修割","配料","滚揉","腌制","焯水","煎制","炒制","油炸","煮制","冷却","速冻","包装","金检","研发取样"];const materialRoles=[{label:"主料",value:"PRIMARY"},{label:"辅料",value:"AUXILIARY"},{label:"加工用水",value:"PROCESS_WATER"}];const sourceTypes=[{label:"外部物料",value:"EXTERNAL"},{label:"前序中间产物",value:"STEP_OUTPUT"}];const states=[{label:"固体",value:"SOLID"},{label:"液体",value:"LIQUID"},{label:"半固体",value:"SEMI_SOLID"}];const outputTypes=[{label:"中间产物",value:"INTERMEDIATE"},{label:"成品",value:"FINISHED"},{label:"合格产出",value:"QUALIFIED"},{label:"余料",value:"REUSABLE"},{label:"尾料",value:"TAILING"},{label:"取样",value:"SAMPLE"},{label:"废弃",value:"WASTE"}];const stepTypes=[{label:"普通操作",value:"NORMAL"},{label:"称重点",value:"WEIGH"},{label:"物料变化",value:"MATERIAL_CHANGE"},{label:"研发取样",value:"SAMPLE"},{label:"废弃节点",value:"WASTE"}];
const stepYield=computed(()=>selectedStep.value?calculateMinorStepYield(selectedStep.value):{mainYieldPercent:null});const majorYield=computed(()=>calculateMajorProcessYield(major.value));watch(()=>major.value.steps.length,length=>{if(!length)selectedIndex.value=0;else selectedIndex.value=Math.min(selectedIndex.value,length-1);});
function commit(){emit("update:modelValue",normalizeProcessPlan({versionNo:0,status:"DRAFT",majorProcesses:[structuredClone(major.value)]}).majorProcesses[0]!);}function newStep(name=""):MinorProcessStepDraft{return{key:nextProcessKey("step"),sequence:major.value.steps.length+1,stepCode:"",stepName:name,stepType:"NORMAL",parameter1Name:"",parameter1Value:"",parameter1Unit:"",parameter2Name:"",parameter2Value:"",parameter2Unit:"",equipment:"",instruction:"",materials:[],outputs:[],controlPoints:[]};}
function addStep(name=""){if(props.readonly)return;major.value.steps.push(newStep(name));selectedIndex.value=major.value.steps.length-1;commit();}function copyStep(){if(props.readonly||!selectedStep.value)return;const next=structuredClone(selectedStep.value);next.id=undefined;next.key=nextProcessKey("step");next.stepName=`${next.stepName}（副本）`;next.materials.forEach(item=>{item.id=undefined;item.key=nextProcessKey("material");});(next.outputs||[]).forEach(item=>{item.id=undefined;item.key=nextProcessKey("output");item.id=item.key;});(next.controlPoints||[]).forEach(point=>{point.id=undefined;point.key=nextProcessKey("control");point.measurements.forEach(measurement=>{measurement.id=undefined;measurement.key=nextProcessKey("measurement");});});selectedIndex.value++;major.value.steps.splice(selectedIndex.value,0,next);commit();}function removeStep(){if(props.readonly)return;major.value.steps.splice(selectedIndex.value,1);commit();}
function addMaterial(){if(!selectedStep.value)return;selectedStep.value.materials.push({key:nextProcessKey("material"),sequence:selectedStep.value.materials.length+1,materialRole:"AUXILIARY",materialName:"",materialState:"SOLID",sourceType:"EXTERNAL"});}function addOutput(){if(!selectedStep.value)return;outputs.value.push({id:nextProcessKey("output"),key:nextProcessKey("output"),sequence:outputs.value.length+1,outputType:"INTERMEDIATE",outputName:"",materialState:"SOLID",primaryOutput:false,continueFlow:true});}
function onSourceChange(material:ProcessStepMaterialDraft){if(material.sourceType==="EXTERNAL")delete material.sourceStepOutputId;else {material.materialCode=undefined;material.formulaMaterialId=undefined;}}function previousOutputsFor(material:ProcessStepMaterialDraft){return material.materialRole==="PRIMARY"?previousOutputs.value.filter(item=>item.output.primaryOutput):previousOutputs.value;}function applyOutputSource(material:ProcessStepMaterialDraft){const output=previousOutputs.value.find(item=>item.value===material.sourceStepOutputId)?.output;if(output){material.materialName=output.outputName;material.materialState=output.materialState;material.weightKg=output.weightKg;}}function ensurePrimaryMaterial(material:ProcessStepMaterialDraft){if(material.materialRole==="PRIMARY")selectedStep.value?.materials.forEach(item=>{if(item!==material)item.materialRole="AUXILIARY";});if(material.sourceType==="STEP_OUTPUT"&&!previousOutputsFor(material).some(item=>item.value===material.sourceStepOutputId))delete material.sourceStepOutputId;}function ensurePrimaryOutput(output:StepOutputDraft){if(output.primaryOutput)outputs.value.forEach(item=>{if(item!==output)item.primaryOutput=false;});}
function dragTemplate(event:DragEvent,name:string){dragPayload.value={kind:"template",name};event.dataTransfer?.setData("application/rnd-step",JSON.stringify(dragPayload.value));}function dragExisting(event:DragEvent,index:number){dragPayload.value={kind:"existing",index};event.dataTransfer?.setData("application/rnd-step",JSON.stringify(dragPayload.value));}function payload(event:DragEvent){try{return JSON.parse(event.dataTransfer?.getData("application/rnd-step")||"")}catch{return dragPayload.value;}}function dropAt(event:DragEvent,index:number){if(props.readonly)return;const data=payload(event);if(data?.kind==="template"){major.value.steps.splice(index,0,newStep(data.name));}else if(data?.kind==="existing"&&data.index!==index){const [step]=major.value.steps.splice(data.index,1);if(step)major.value.steps.splice(index,0,step);}commit();}
function parameterSummary(step:MinorProcessStepDraft){return [[step.parameter1Name,step.parameter1Value,step.parameter1Unit].filter(Boolean).join(" "),[step.parameter2Name,step.parameter2Value,step.parameter2Unit].filter(Boolean).join(" ")].filter(Boolean).join(" · ")||"关键参数待设置";}function percent(value:number|null){return value==null?"待补充":`${value.toFixed(2)}%`;}
</script>
<style scoped>
.minor-workspace{display:grid;grid-template-columns:220px minmax(0,1fr);min-height:520px;border:1px solid #e5e6eb;border-radius:12px;overflow:hidden;background:#f6f7f9}.step-rail{display:grid;align-content:start;gap:7px;padding:14px;background:#fff;border-right:1px solid #e5e6eb}.rail-heading small,.step-item small,.crumb,.editor-header p,.hint{display:block;color:#86909c;font-size:12px}.step-item{text-align:left;padding:10px;border:1px solid transparent;border-radius:8px;background:#f7f8fa;cursor:grab}.step-item.active{border-color:#91caff;background:#e6f4ff}.step-item span{display:inline-block;width:26px;color:#1677ff;font-size:12px}.step-item b{font-size:13px}.step-templates{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px;padding-top:10px;border-top:1px solid #f0f0f0}.step-templates button{border:1px solid #d9d9d9;border-radius:5px;background:#fff;padding:4px 7px;font-size:12px;cursor:grab}.step-editor{display:grid;align-content:start;gap:10px;padding:16px;overflow:auto}.editor-header{display:flex;justify-content:space-between;align-items:start}.editor-header h3{margin:3px 0}.editor-header p{margin:0}.section{padding:13px;border:1px solid #e5e6eb;border-radius:10px;background:#fff}.section-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;color:#595959;font-size:13px}.hint{margin:0 0 8px}.material-row,.output-row{display:grid;gap:6px;align-items:center;margin-top:6px}.material-row{grid-template-columns:118px 110px 100px 90px minmax(120px,1fr) 120px 45px}.output-row{grid-template-columns:110px minmax(120px,1fr) 82px 120px 82px 82px 130px 45px}.live{display:grid;grid-template-columns:1fr 1fr;gap:12px;background:#f0f7ff}.live b,.live span{display:block}.live span{margin-top:3px;color:#1677ff}.no-step{display:grid;place-content:center;min-height:300px;color:#86909c}@media(max-width:1100px){.minor-workspace{grid-template-columns:180px minmax(0,1fr)}.material-row,.output-row{grid-template-columns:repeat(2,minmax(0,1fr))}.summary-grid{grid-template-columns:1fr}}
</style>
