<template>
  <section class="workspace"><header class="workspace-top"><div class="title"><span class="eyebrow">研发工艺工作台</span><h2>工艺、配方与 SOP</h2><div class="tags"><a-tag :color="plan.status==='SUBMITTED'?'green':'blue'">{{ plan.status==='SUBMITTED' ? `正式版本 R${selectedRevision?.revisionNo || ''}` : '草稿' }}</a-tag><span :class="`save-${saveState}`">{{ saveLabel }}</span></div></div><div class="top-summary"><span>大工序 <b>{{ plan.majorProcesses.length }}</b></span><span>小步骤 <b>{{ stepCount }}</b></span><span>最终得率 <b>{{ percent(finalYield) }}</b></span></div><a-space><a-button :disabled="readonly || plan.status !== 'DRAFT'" :loading="saveState==='saving'" @click="saveNow">保存草稿</a-button><a-button type="primary" :disabled="readonly || !formId || plan.status !== 'DRAFT' || saveState === 'saving'" @click="openSubmit">正式提交</a-button></a-space></header>
    <div class="workspace-main"><div v-if="activeMajorIndex === null" class="view"><div class="view-bar"><div><b>大工序编排</b><small>拖拽排序；模板可重复使用；进入后维护小步骤</small></div></div><MajorProcessBoard v-model="plan" :readonly="readonly" :selected-index="activeMajorIndex ?? undefined" @select="openMajor" /></div>
      <div v-else class="view"><div class="breadcrumb"><a-button type="link" @click="activeMajorIndex=null">‹ 返回大工序</a-button><span>工艺工作台 / {{ plan.majorProcesses[activeMajorIndex]?.processName }}</span></div><MinorStepWorkspace v-if="plan.majorProcesses[activeMajorIndex]" v-model="plan.majorProcesses[activeMajorIndex]" :readonly="readonly" /></div>
      <aside class="side"><section class="side-card"><div class="side-title"><b>版本历史</b><a-button size="small" type="link" @click="loadRevisions">刷新</a-button></div><a-empty v-if="!revisions.length" :image="false" description="尚未提交正式版本" /><button v-for="revision in revisions" :key="revision.id" class="revision" @click="loadRevision(revision.id)"><b>R{{ revision.revisionNo }}</b><span>{{ formatDate(revision.submittedAt) }}</span><small>{{ revision.changeReason || '首次正式提交' }}</small></button><a-descriptions v-if="selectedRevision" size="small" :column="1" bordered style="margin:8px 0"><a-descriptions-item label="查看版本">R{{ selectedRevision.revisionNo }}</a-descriptions-item><a-descriptions-item label="提交时间">{{ formatDate(selectedRevision.submittedAt) }}</a-descriptions-item><a-descriptions-item label="变更原因">{{ selectedRevision.changeReason || '首次正式提交' }}</a-descriptions-item></a-descriptions><a-button v-if="selectedRevision && !readonly" block type="dashed" @click="openNewDraft">从此版本新建草稿</a-button></section><RndOutputCenter :form-id="formId" :revisions="revisions" :readonly="readonly" /></aside>
    </div>
    <a-modal v-model:open="newDraftOpen" title="从正式版本新建草稿" ok-text="新建草稿" :ok-button-props="{disabled:!newDraftReason.trim()}" @ok="createDraft"><p>将复制 R{{ selectedRevision?.revisionNo }} 为新的可编辑草稿，正式版本保持不变。</p><a-form layout="vertical"><a-form-item label="变更原因（必填）"><a-textarea v-model:value="newDraftReason" :rows="3" placeholder="说明为何需要修改工艺" /></a-form-item><a-checkbox v-model:checked="newDraftConfirmed">我确认将基于该正式版本创建新草稿</a-checkbox></a-form><template #footer><a-button @click="newDraftOpen=false">取消</a-button><a-button type="primary" :disabled="!newDraftReason.trim() || !newDraftConfirmed" @click="createDraft">新建草稿</a-button></template></a-modal>
    <ProcessSubmitDialog v-model:open="showSubmit" :form-id="formId" :plan="plan" :ready="saveState !== 'dirty' && saveState !== 'saving'" @submitted="onSubmitted" />
  </section>
</template>
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { message } from "ant-design-vue";
import { calculateBatchYield, normalizeProcessPlan, type ProcessPlanDraft, type ProcessRevision, type ProcessRevisionSummary } from "@rnd/shared";
import { api } from "../../services/api";
import MajorProcessBoard from "./MajorProcessBoard.vue";
import MinorStepWorkspace from "./MinorStepWorkspace.vue";
import ProcessSubmitDialog from "./ProcessSubmitDialog.vue";
import RndOutputCenter from "./RndOutputCenter.vue";
import { ProcessPlanSaveCoordinator } from "./processPlanAutosave";
const props=defineProps<{modelValue:ProcessPlanDraft;formId?:string;readonly?:boolean;hydrating?:boolean}>();const emit=defineEmits<{"update:modelValue":[value:ProcessPlanDraft];"request-save":[];"saved":[value:ProcessPlanDraft]}>();
const plan=computed({get:()=>props.modelValue,set:value=>emit("update:modelValue",normalizeProcessPlan(value))});const activeMajorIndex=ref<number|null>(null);const saveState=ref<"idle"|"dirty"|"saving"|"saved"|"error">("idle");const revisions=ref<ProcessRevisionSummary[]>([]);const selectedRevision=ref<ProcessRevisionSummary>();const showSubmit=ref(false);const newDraftOpen=ref(false);const newDraftReason=ref("");const newDraftConfirmed=ref(false);let hydrated=false;let applyingServerAck=false;let formGeneration=0;let coordinator:ProcessPlanSaveCoordinator<ProcessPlanDraft>|undefined;
const stepCount=computed(()=>plan.value.majorProcesses.reduce((count,major)=>count+major.steps.length,0));const finalYield=computed(()=>calculateBatchYield(plan.value));const saveLabel=computed(()=>({idle:"",dirty:"待保存",saving:"正在保存",saved:"已保存",error:"保存失败，请重试"}[saveState.value]));
onMounted(()=>{coordinator=new ProcessPlanSaveCoordinator<ProcessPlanDraft>({debounceMs:1200,isDraft:value=>value.status==="DRAFT",mergeAck:(local,ack)=>normalizeProcessPlan({...local,versionNo:ack.versionNo,status:ack.status,sourceRevisionId:ack.sourceRevisionId,changeReason:ack.changeReason,balanceToleranceKg:ack.balanceToleranceKg}),save:value=>api.task.saveProcessPlan(props.formId!,{...normalizeProcessPlan(value),experimentFormId:props.formId}),onChange:(value,state)=>{saveState.value=state;if(state==="saved"){applyingServerAck=true;plan.value=value;void nextTick().then(()=>applyingServerAck=false);emit("saved",value);}},onError:error=>message.error(error instanceof Error?error.message:"工艺草稿保存失败，请刷新后比较差异")});coordinator.hydrate(normalizeProcessPlan(plan.value));hydrated=true;});onBeforeUnmount(()=>{formGeneration++;coordinator?.dispose();});watch(()=>props.formId,async id=>{formGeneration++;revisions.value=[];selectedRevision.value=undefined;activeMajorIndex.value=null;if(id){coordinator?.hydrate(normalizeProcessPlan(plan.value));await loadRevisions();}},{immediate:true});watch(()=>props.modelValue,()=>{if(!hydrated||props.hydrating||applyingServerAck)return;try{coordinator?.edit(()=>normalizeProcessPlan(plan.value));}catch(error){saveState.value="error";message.error(error instanceof Error?error.message:"工艺数据无法保存");}},{deep:true});
function openMajor(index:number){activeMajorIndex.value=index;}async function saveNow(silent=false){if(props.readonly)return;if(!props.formId){emit("request-save");return;}try{await coordinator?.flush();if(!silent&&saveState.value==="saved")message.success("工艺草稿已保存");}catch(error){saveState.value="error";if(!silent)message.error(error instanceof Error?error.message:"保存失败");}}
async function openSubmit(){await saveNow(true);if(saveState.value!=="error"&&saveState.value!=="saving")showSubmit.value=true;}
defineExpose({flushSave:saveNow});
async function loadRevisions(){if(!props.formId)return;try{revisions.value=await api.task.getProcessRevisions(props.formId);if(!selectedRevision.value&&revisions.value[0])selectedRevision.value=revisions.value[0];}catch(error){message.error(error instanceof Error?error.message:"无法加载版本历史");}}async function loadRevision(id:string){if(!props.formId)return;try{const revision=await api.task.getProcessRevision(props.formId,id);selectedRevision.value=revision;message.info(`已查看正式版本 R${revision.revisionNo}；如需编辑请从此版本新建草稿`);}catch(error){message.error(error instanceof Error?error.message:"无法读取版本详情");}}
function openNewDraft(){newDraftReason.value="";newDraftConfirmed.value=false;newDraftOpen.value=true;}async function createDraft(){if(!props.formId||!selectedRevision.value||!newDraftReason.value.trim()||!newDraftConfirmed.value)return;try{const draft=await api.task.createDraftFromRevision(props.formId,selectedRevision.value.id,newDraftReason.value.trim());plan.value=normalizeProcessPlan(draft);activeMajorIndex.value=null;newDraftOpen.value=false;saveState.value="saved";message.success("已从正式版本创建新草稿");}catch(error){message.error(error instanceof Error?error.message:"新建草稿失败");}}
async function onSubmitted(revision:ProcessRevision){coordinator?.dispose();revisions.value=[revision,...revisions.value.filter(item=>item.id!==revision.id)];selectedRevision.value=revision;applyingServerAck=true;plan.value=normalizeProcessPlan(revision.snapshot);await nextTick();applyingServerAck=false;saveState.value="saved";await loadRevisions();}function percent(value:number|null|undefined){return value==null?"待补充":`${value.toFixed(2)}%`;}function formatDate(value:string){return value?new Date(value).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"";}
</script>
<style scoped>
.workspace{display:grid;gap:12px;padding:14px;border-radius:12px;background:#f5f6f8}.workspace-top{display:flex;align-items:center;gap:20px;padding:14px 16px;border:1px solid #e5e6eb;border-radius:12px;background:#fff}.title{min-width:200px}.eyebrow{color:#1677ff;font-size:12px;font-weight:600}.title h2{margin:2px 0 5px;font-size:20px}.tags{display:flex;gap:8px;align-items:center;font-size:12px;color:#86909c}.save-saving{color:#1677ff}.save-error{color:#cf1322}.save-saved{color:#389e0d}.top-summary{display:flex;gap:16px;flex:1;color:#595959;font-size:13px}.top-summary b{display:block;color:#262626;font-size:17px}.workspace-main{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:12px}.view,.side-card{padding:12px;border:1px solid #e5e6eb;border-radius:12px;background:#fff}.view-bar{display:flex;justify-content:space-between;margin-bottom:10px}.view-bar small{display:block;color:#86909c;font-size:12px;margin-top:3px}.breadcrumb{display:flex;align-items:center;gap:6px;margin-bottom:9px;color:#86909c;font-size:12px}.side{display:grid;align-content:start;gap:12px}.side-title{display:flex;justify-content:space-between;align-items:center}.revision{display:grid;width:100%;grid-template-columns:36px 1fr;text-align:left;padding:9px 0;border:0;border-top:1px solid #f0f0f0;background:#fff;cursor:pointer}.revision span,.revision small{font-size:12px;color:#86909c}.revision small{grid-column:2}.side-card :deep(.ant-empty){margin:12px 0}@media(max-width:1120px){.workspace-main{grid-template-columns:1fr}.side{grid-template-columns:1fr 1fr}.workspace-top{flex-wrap:wrap}.top-summary{order:3;flex-basis:100%}}@media(max-width:760px){.side{grid-template-columns:1fr}}
</style>
