<template>
  <section class="output-center"><header><div><b>成果输出中心</b><small>所有文件均绑定正式工艺版本</small></div><a-select v-if="revisions.length" v-model:value="selectedRevisionId" size="small" style="width:150px" :options="revisionOptions" /></header>
    <a-empty v-if="!selectedRevisionId" description="正式提交后可生成配方与 SOP" :image="false" />
    <template v-else><div v-for="type in artifactTypes" :key="type.value" class="artifact"><div><b>{{ type.label }}</b><small>{{ artifactFor(type.value)?.documentVersion || '尚未生成' }} · {{ statusLabel(artifactFor(type.value)?.status) }}</small></div><a-space><a-button v-if="!readonly" size="small" :loading="generating===type.value" @click="generate(type.value)">{{ artifactFor(type.value) ? '重新生成' : '生成' }}</a-button><a-button v-if="artifactFor(type.value)?.status==='READY'" size="small" type="link" @click="download(artifactFor(type.value)!.id)">下载</a-button></a-space></div>
      <div class="pricing-wait"><b>生产核价</b><span>等待包装确认后由现有核价流程生成</span></div></template>
  </section>
</template>
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { message } from "ant-design-vue";
import type { ProcessArtifact, ProcessArtifactType, ProcessRevisionSummary } from "@rnd/shared";
import { api } from "../../services/api";
const props=defineProps<{formId?:string;revisions:ProcessRevisionSummary[];readonly?:boolean}>();const selectedRevisionId=ref<string>();const artifacts=ref<ProcessArtifact[]>([]);const generating=ref<ProcessArtifactType>();const artifactTypes=[{label:"标准配方 Formula",value:"FORMULA_XLSX" as const},{label:"生产 SOP",value:"SOP_DOCX" as const}];const revisions=computed(()=>props.revisions);const revisionOptions=computed(()=>revisions.value.map(item=>({label:`正式版本 R${item.revisionNo}`,value:item.id})));watch(revisions,value=>{if(!selectedRevisionId.value&&value[0])selectedRevisionId.value=value[0].id;},{immediate:true});watch(selectedRevisionId,()=>void loadArtifacts());async function loadArtifacts(){if(!props.formId||!selectedRevisionId.value)return;try{artifacts.value=await api.task.getProcessArtifacts(props.formId,selectedRevisionId.value);}catch{artifacts.value=[];}}function artifactFor(type:ProcessArtifactType){return artifacts.value.find(item=>item.artifactType===type);}function statusLabel(status?:string){return status==="READY"?"已就绪":status==="FAILED"?"生成失败":"待生成";}async function generate(type:ProcessArtifactType){if(!props.formId||!selectedRevisionId.value)return;generating.value=type;try{const result=await api.task.generateProcessArtifact(props.formId,selectedRevisionId.value,type);artifacts.value=[...artifacts.value.filter(item=>item.artifactType!==type),result];message.success("文件已生成");}catch(error){message.error(error instanceof Error?error.message:"生成失败");}finally{generating.value=undefined;}}async function download(id:string){if(!props.formId||!selectedRevisionId.value)return;try{const blob=await api.report.downloadProcessArtifact(props.formId,selectedRevisionId.value,id);const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="工艺成果";link.click();URL.revokeObjectURL(url);}catch(error){message.error(error instanceof Error?error.message:"下载失败");}}
</script>
<style scoped>
.output-center{padding:12px;border:1px solid #e5e6eb;border-radius:10px;background:#fff}.output-center header,.artifact,.pricing-wait{display:flex;align-items:center;justify-content:space-between;gap:12px}.output-center header{margin-bottom:8px}.output-center small,.artifact small{display:block;color:#86909c;font-size:12px}.artifact,.pricing-wait{padding:10px 0;border-top:1px solid #f0f0f0}.pricing-wait span{color:#86909c;font-size:12px}
</style>
