package com.lhr.rnd.domain;

public enum SampleStatus {
    PENDING_REVIEW,
    PENDING_ASSIGNMENT,
    PENDING_ACCEPTANCE,
    SAMPLING,
    PENDING_TEST,
    SAMPLE_COMPLETED,
    RESAMPLING_REQUIRED,
    PENDING_PRICING_REVIEW,
    PRICING_APPROVED,
    PRICING_REJECTED,
    FINANCE_NOTIFIED,
    ARCHIVED,
    STOPPED
}
