spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rnd_sample
    username: rnd_sample
    password: rnd_sample
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
